### ISSUE TITLE
k8s version not defined in vars

### ISSUE THREAD

**Issue by holynakamoto** [finleap/tf-eks-fargate-tmpl#5]
main.tf L#25

**Comment by holynakamoto** [comment]
https://github.com/holynakamoto/tf-eks-fargate-tmpl/commit/1221f6af36144c42df75566db841138db6931f82

**Comment by ajantsch** [comment]
https://github.com/finleap/tf-eks-fargate-tmpl/commit/7e550c16a6978bd9067ab968f8c77591cb0bcb6e
